### ISSUE TITLE
Create text interface for TTS

### ISSUE THREAD

**Issue by jerivl** [jluckenbaugh2/Deepcut#3]
**Issue:** Need to be able to run TTS easily

**Task:** Create function that creates audio from text using pytorch implementation of tacotron2
https://github.com/NVIDIA/tacotron2

**Desired input:** Input string, sample rate

**Desired output:** Numpy array containing audio data

Prefer sample rate = 44.1k but 16k at minimum

**Comment by hamzabhatti12** [comment]
Here is the traceback from the error I am getting:

Using cache found in C:\Users\Hamza/.cache\torch\hub\nvidia_DeepLearningExamples_torchhub
Traceback (most recent call last):
  File "C:\Users\Hamza\Documents\GitHub\Deepcut\tests\tacotron\tacotron.py", line 3, in <module>
    tacotron2 = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_tacotron2')
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\hub.py", line 353, in load
    model = entry(*args, **kwargs)
  File "C:\Users\Hamza/.cache\torch\hub\nvidia_DeepLearningExamples_torchhub/hubconf.py", line 131, in nvidia_tacotron2
    from PyTorch.SpeechSynthesis.Tacotron2.models import lstmcell_to_float, batchnorm_to_float
  File "C:\Users\Hamza/.cache\torch\hub\nvidia_DeepLearningExamples_torchhub\PyTorch\SpeechSynthesis\Tacotron2\models.py", line 32, in <module>
    from tacotron2.model import Tacotron2
  File "C:\Users\Hamza\Documents\GitHub\Deepcut\tests\tacotron\tacotron2\model.py", line 6, in <module>
    from layers import ConvNorm, LinearNorm
ModuleNotFoundError: No module named 'layers'

**Comment by jerivl** [comment]
Have you tried pasting in the code from https://github.com/NVIDIA/tacotron2/blob/master/model.py into your working directory?

It just seems like a linking problem to me, but I can't remember if you said that there was something else in our meetings.
